use_frameworks!

platform :ios, '12.0'

# 注：如果没有下载SDK，请直接执行后面代码：  sh init.sh

def pod_audioEffect(type) 
  pod "TXLiteAVSDK_#{type}",:path => "../../SDK/"
  pod 'TUIAudioEffect', :path => "../", :subspecs => ["#{type}"]
end

target 'TUIAudioEffectView_Example' do
  pod 'TXAppBasic', :path => "./TXAppBasic/"
  pod 'TUICore', :path => '../../TUICore'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Toast-Swift'
  pod 'Alamofire'
  pod_audioEffect('Professional')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
