# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TUILiveRoomApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TXAppBasic', :path => "TXAppBasic/"
  pod 'TCBeautyKit', :path => "TCBeautyKit/"
  pod 'TXLiteAVSDK_TRTC'
  pod 'TUILiveRoom', :path => "./", :subspecs => ["TRTC"]
end
