# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TUILiveRoomApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TUICore', '~> 7.3.4358'
  pod 'TXLiteAVSDK_TRTC'
  pod 'TXAppBasic', :path => "../TXAppBasic/"
  pod 'TUIBeauty', :path => "../TUIBeauty/"
  pod 'TUIBarrage', :path => "../TUIBarrage/"
  pod 'TUIGift', :path => "../TUIGift/"
  pod 'TUIAudioEffect', :path => "../TUIAudioEffect/", :subspecs => ["TRTC"]
  pod 'TUILiveRoom', :path => "../", :subspecs => ["TRTC"]
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
